services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    # Traefik stuff
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dozzle.rule=Host(`__DOMAIN__`) && PathPrefix(`/dozzle`)"
      - "traefik.http.services.dozzle.loadbalancer.server.port=8080"
      - "traefik.http.routers.dozzle.entrypoints=websecure"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    environment:
      DOZZLE_AUTH_PROVIDER: simple
      DOZZLE_BASE: /dozzle
networks:
  default:
    name: traefik
    external: true